on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: semrel
        uses: thegrumpylion/semrel-action@main
      - run: echo next-ver = $NEXT_VERSION
        shell: bash
        env:
          NEXT_VERSION: ${{ steps.semrel.outputs.next-version }}
      - run: echo current-ver = $CURRENT_VERSION
        shell: bash
        env:
          CURRENT_VERSION: ${{ steps.semrel.outputs.current-version }}
